# Generated by Django 3.2.7 on 2021-09-17 01:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0002_alter_pokemon_pokemon_id'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='pokemon',
            unique_together={('id', 'pokemon_id')},
        ),
    ]
