# Generated by Django 3.2.7 on 2021-09-17 02:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0004_auto_20210917_0217'),
    ]

    operations = [
        migrations.AddField(
            model_name='pokemon',
            name='prevolution',
            field=models.ManyToManyField(related_name='_command_pokemon_prevolution_+', to='command.Pokemon', verbose_name='prevolution'),
        ),
    ]
