# Generated by Django 3.2.7 on 2021-09-17 18:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('command', '0005_pokemon_prevolution'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stat',
            name='pokemon',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='stats', to='command.pokemon'),
        ),
    ]
